Standardise routes
TomYoungs/SAD-Group-Project pull request #21
Opened 2022-11-27 22:41 UTC by JacobAsuman

# What is being *changed? 🤔

*Standardised routes
* Some GET functions
*Some GET request urls

# Has change been tested and works fully? 🤖
- [ ] yes

# Does this complete a Ticket? 🎟️
- [ ] yes

2022-11-27 22:51 UTC, TomYoungs requested changes

2022-11-27 22:51 UTC, TomYoungs commented on backend/server.js
> +            console.log(`listening on port ${PORT}!\nhttp://localhost:3000`)
It is port 4000 not 3000 in package.json there is a proxy that routes it to 3000 for local testing

2022-11-28 12:48 UTC, Rickemon approved these changes

2022-11-28 19:06 UTC, TomYoungs approved these changes

2022-11-28 19:06 UTC, merged